- name: Report updates for Windows WMs
  hosts: all
  gather_facts: true
  vars:
    user_state: ""
    username: "{{ username }}"
  tasks:
    - name: check user
      win_user:
        name: "{{ username }}"
        state: query
      register: result_user


    - name: set user state
      set_fact:
        user_state: "User does not exist"    
  

    - debug: var=result_user
  
    - name: set user state
      set_fact:
        user_state: User exists
      when: result_user.state == "present"
      ignore_errors: yes

    - debug: var=user_state

    - name: get date
      set_fact:
        date="{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"


    - name: Create HTMl report
      template:
        src: report-windows-user.j2
        dest: /tmp/report-check-windows-user-{{ date }}.html
      delegate_to: KSANSIBLEPOCT1.SIMCACLS.LOCAL
      run_once: true