- name: Check if a Linux user exists
  hosts: all
  vars:
    checkuser: []
    username: "{{ username }}"
  tasks:
  - name: Check if user exists
    getent:
      database: passwd
      key: "{{ username }}"
      fail_key: False
    become: true
    register: result
  
  - name: set fact user
    set_fact:
      username: "{{ username }}"

  - name: set user state
    set_fact:
      user_state: "User does not exist"    
  
  - debug: var=getent_passwd
  
  - debug: var=result

  - debug: var=ansible_facts.getent_passwd

  - debug: var=username

  - debug: var=""{{ username }}""

  - name: set fact result
    set_fact:
      checkuser: "{{ getent_passwd }}"

#  - debug: var=checkuser
 
  - name: set user state
    set_fact:
      user_state: User exists
    when: ansible_facts.getent_passwd.{{ username }}[3] == username
    ignore_errors: yes
#  - debug: var=ansible_facts.getent_passwd.{{ username }}[3]
#  - debug: var=username
  - debug: var=user_state

  - debug: var=ansible_facts.getent_passwd.{{ username }}[3]
  
 # - debug: var="{{ username }}"
 # - debug: var={{ username }}

  - name: get date
    set_fact:
      date="{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"

  - name: Create HTMl report
    template:
      src: report-check-linux-user.j2
      dest: /tmp/report-check-linux-user-{{ date }}.html
    delegate_to: KSANSIBLEPOCT1.SIMCACLS.LOCAL
    run_once: true