- name: Check if a Linux user exists
  hosts: all
  tasks:
  - name: Check if user exists
    getent:
      database: passwd
      key: "{{ user_name }}"
      fail_key: False
    become: true
    register: result
  
  - name: set fact user
    set_fact:
      username: "{{ user_name }}"
  
  - debug: var=getent_passwd
  
  - debug: var=result

  - name: set fact result
    set_fact:
      checkuser: "{{ result.ansible_facts.getent_passwd }}"

  - name: get date
    set_fact:
      date="{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"

  - name: Create HTMl report
    template:
      src: report-check-linux-user.j2
      dest: /tmp/report-check-linux-user-{{ date }}.html
    delegate_to: tower-01
    run_once: true
