- name: Report updates for Windows WMs
  hosts: windows
  gather_facts: true
  vars:
    userstate: ""

  tasks:
    - name: check user
      win_user:
        name: Administrator3
        state: query
      register: result_user

    - debug: var=result_user
    
#    - debug: var=ansible_facts 
    

    - name: get date
      set_fact:
        date="{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"


    - name: Create HTMl report
      template:
        src: report-windows-user.j2
        dest: /tmp/report-windows-updates-{{ date }}.html
      delegate_to: KSANSIBLEPOCT1.SIMCACLS.LOCAL
      run_once: true