- name: Check if a Linux user exists
  hosts: all
  tasks:
  - name: Check if user exists
    getent:
      database: passwd
      key: "{{ user_name }}"
      fail_key: False
    register: getent_password
    become: true
  - debug: var=getent_password 
