- name: Check if a Linux user exists
  hosts: all
  tasks:
  - name: Check if user exists
    getent:
      database: passwd
      key: "{{ user_name }}"
      fail_key: False
    become: true
  register: result
    
  - debug: var=result
