- name: Report updates for Windows WMs
  hosts: all
  gather_facts: true
  vars:
    updatelist: []
  tasks:
    - name: update tasks for Red Hat
      block: 
      - name: install yum-utils
        yum:
          name: yum-utils
          state: latest
        become: true
      
      - name: list updates Red Hat
        yum:
          list: updates
          use_backend: yum3
        register: update_result

      - name: create array for updates Red Hat
        set_fact:
          updatelist: "{{ update_result.results | map(attribute='envra') | list }}"
        register: updatelist_result
      when: ansible_distribution == "RedHat" or ansible_distribution == "Fedora"

    - name: update tasks for Ubuntu
      block: 
      - name: list updates Ubuntu
        command: 'apt list --upgradeable'
        register: update_result
        
      - name: create arrays for update Ubuntu
        set_fact:
          updatelist: "{{ update_result | json_query(jmesquery) }}"
        vars:
          jmesquery: 'stdout_lines'
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: get date
      set_fact:
        date="{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"

    - name: Create HTMl report
      template:
        src: report-linux-updates.j2
        dest: /tmp/report-{{ date }}.html
      delegate_to: tower-01
      run_once: true