- name: Report updates for Windows WMs
  hosts: linux
  gather_facts: true
  vars:
    updatelist: []
  tasks:
    - name: install yum-utils
      yum:
        name: yum-utils
        state: latest
      become: true

    - name: list updates
      yum:
        list: updates
        use_backend: yum3
      register: update_result
    
    - debug: var=update_result
    
#    - debug: var=ansible_facts

    - name: create array for updates
      set_fact:
        updatelist: "{{ update_result.results | map(attribute='envra') | list }}"
      register: updatelist_result
    
    - name: get date
      set_fact:
        date="{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"

    - name: Delete old report
      file:
        path: /tmp/report-{{ date }}.html
        state: absent
      delegate_to: tower-01

    - name: Create HTMl report
      template:
        src: report-linux-updates.j2
        dest: /tmp/report-{{ date }}.html
      delegate_to: tower-01
      run_once: true