- name: Report updates for Windows WMs
  hosts: windows
  gather_facts: true
  vars:
    updatelist: []
  tasks:
    - debug: var=ansible_facts

    - name: Check for updates 
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: searched
        log_path: C:\ansible_wu.txt
      register: update_result
 
    - name: print titles of updates
      debug: msg=""{{ update_result | json_query(jmesquery) }}""
      vars:
        jmesquery: '*.*.title[]'

    - name: edit list for updates
      set_fact:
        updatelist: "{{ update_result | json_query(jmesquery) }}"
      vars:
        jmesquery: '*.*.title[]'

    - name: Delete old report
      file:
        path: /tmp/report.html
        state: absent
      delegate_to: localhost

    - name: Create HTMl report
      template:
        src: report-windows-updates.j2
        dest: /tmp/report.html
      delegate_to: localhost
      run_once: true